MVC2/Models/broker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public broker()
        {
            this.appointments = new HashSet<appointment>();
        }
    
        public int idBroker { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string mail { get; set; }
        public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointments { get; set; }
    }
}

MVC2/Controllers/AppointmentController.cs
using MVC2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC2.Controllers
{
    public class AppointmentController : Controller
    {
        private NoteBookEntities1 db = new NoteBookEntities1();

        public ActionResult SuccessAddAppointment()
        {
            return View();
        }
        // GET: Appointment
        public ActionResult AddAppointment(int? id)
        {
            if (id == null)
            {
                ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastName");
                ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastName");
                return View();
            }
            else // Via un ID par la liste
            {
                ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastName", id);
                ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastName");
                return View();
            }

        }
        // Instanciation du constructeur
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAppointment([Bind(Include = "idAppointment, dateHour, idBroker, idCustomer")] appointment AppointmentToAdd)
        {
            var date = Request.Form["trip-start"];
            var hour = Request.Form["horaire"];
            var datatime = date + " " + hour;
            AppointmentToAdd.dateHour = Convert.ToDateTime(datatime);
            var isAlreadyUsed = db.appointments.Where(appoint => appoint.dateHour == AppointmentToAdd.dateHour && appoint.idBroker == AppointmentToAdd.idBroker || appoint.dateHour == AppointmentToAdd.dateHour && appoint.idCustomer == AppointmentToAdd.idCustomer).SingleOrDefault();

        // je dois recupérer le datetime de la classe addAppointment et les ajouter dans une database de type dateTime ici 

            if(string.IsNullOrEmpty(date) || string.IsNullOrEmpty(hour))
            {
                ModelState.AddModelError("dateHour", "heure ou date manquante");
            }
            else if (isAlreadyUsed != null)
            {
                ModelState.AddModelError("dateHour", "Le courtier ou le client à déjà rendez-vous de prévu à cette date ");
            }
            if (ModelState.IsValid)
            {
                db.appointments.Add(AppointmentToAdd); // insertion dans la dataBase
                db.SaveChanges(); // enregistre les changements
                return RedirectToAction("SuccessAddAppointment");
            }
            ViewBag.idBroker = new SelectList(db.brokers, "idBroker", "lastName", AppointmentToAdd.idBroker);
            ViewBag.idCustomer = new SelectList(db.customers, "idCustomer", "lastName", AppointmentToAdd.idCustomer);
            return View(AppointmentToAdd);
        }

        private class DisplayName
        {
        }
        //new Dictionary<string, string>
        /* */
    }
}

MVC2/Controllers/BrokerController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using System.Text.RegularExpressions; // Pour l'utilisation des Regex
using MVC2.Models;
using System.Data.Entity;
using System.Net;

namespace MVC2.Controllers
{
    public class BrokerController : Controller
    {
        private NoteBookEntities1 db = new NoteBookEntities1();

        // GET: Une methode qui permet d'afficher le ProfilBroker
        public ActionResult ProfilBroker(int? id) // '?' rendre nullable l'id
        { 
            if (id == null)
            {
                return View("ErrorBadRequest");
            }
            // recupère le broker par son id. 
            broker brokerById = db.brokers.Find(id);
            if (brokerById == null)
            {
                return View("ErrorPageNotFound");
            }
            return View(brokerById);
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult ProfilBroker([Bind(Include = "idBroker,lastName,firstName,mail,phoneNumber")] broker brokerList)
        {
            //Déclaration des Regexs
            string regexName = @"^[A-Za-zéèàêâôûùïüç-]+$";
            string regexMail = @"^[0-9a-zA-Z.-]+@[0-9a-zA-Z.-]+.[a-zA-Z]{2,4}";
            string regexPhone = @"^[0][0-9]{9}";
            //Vérification que le champ lastName ne soit pas incorrect ou null
            if (!String.IsNullOrEmpty(brokerList.lastName))  //si le champ mail n'est pas vide ou null on vérifie la validité de l'entrée
            {
                if (!Regex.IsMatch(brokerList.lastName, regexName))
                {
                    //Message d'erreur
                    ModelState.AddModelError("lastName", "Votre nom n'est pas valide");
                }
            }
            else
            {
                //Message d'erreur si le lastName est vide ou null
                ModelState.AddModelError("lastName", "Veuillez remplir ce champ");
            }
            //Vérification que le champ firstName ne soit pas incorrect ou null
            if (!String.IsNullOrEmpty(brokerList.firstName)) //si le champ firstName n'est pas vide ou null on vérifie la validité de l'entrée
            {
                if (!Regex.IsMatch(brokerList.firstName, regexName)) //si l'entrée utilisateur ne passe pas la regex ajout d'un message d'erreur
                {
                    //Message d'erreur
                    ModelState.AddModelError("firstName", "Votre prénom n'est pas valide");
                }
            }
            else
            {
                //Message d'erreur si le firstName est vide ou null
                ModelState.AddModelError("firstName", "Veuillez remplir ce champ");
            }
            //Vérification que le champ email ne soit pas incorrect ou null
            if (!String.IsNullOrEmpty(brokerList.mail)) //si le champ mail n'est pas vide ou null on vérifie la validité de l'entrée
            {
                if (!Regex.IsMatch(brokerList.mail, regexMail))
                {
                    //Message d'erreur
                    ModelState.AddModelError("mail", "Veuillez écrire un email valide");
                }
            }
            else
            {
                //Message d'erreur si le mail est vide ou null
                ModelState.AddModelError("mail", "Veuillez remplir ce champ");
            }
            if (!String.IsNullOrEmpty(brokerList.phoneNumber)) //si le champ phoneNumber n'est pas vide ou null on vérifie la validité de l'entrée
            {
                if (!Regex.IsMatch(brokerList.phoneNumber, regexPhone))
                {
                    //Message d'erreur
                    ModelState.AddModelError("phoneNumber", "Veuillez saisir un numéro valide");
                }
            }
            else
            {
                //Message d'erreur si le numéro de téléphone est vide ou null
                ModelState.AddModelError("phoneNumber", "Veuillez remplir ce champ");
            }
            if (ModelState.IsValid)
            {
                db.Entry(brokerList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("successAddBroker");
            }
            else
            {
                return View("ProfilBroker");
            }
        }
        //GET: ListBroker
        public ActionResult ListBroker()
        {
            return View(db.brokers.ToList());
        }
        // GET: Broker
        public ActionResult AddBroker()
        {
            return View("AddBroker");
        }
        // Instanciation du constructeur
        [HttpPost]
        public ActionResult AddBroker([Bind(Include = "idBroker, lastName, firstName, mail, phoneNumber")] broker BrokerToAdd)
        {
            string regexName = @"^[A-Za-zéèëêuùçôàö\-]+$";
            string regexMail = @"[0-9a-zA-Z\.\-]+@[0-9a-zA-Z\.\-]+.[a-zA-Z]{2,4}";
            string regexPhone = @"^[0][0-9]{9}";
            if (!string.IsNullOrEmpty(BrokerToAdd.lastName))
            {
                // verification de regex
                if (!Regex.IsMatch(BrokerToAdd.lastName, regexName))
                {
                    ModelState.AddModelError("LastName", "Ecrire un nom valide");
                }
            }
            // Verification si le champs est libre ou pas
            else
            {
                ModelState.AddModelError("LastName", "Ecrire un nom");
            }
            if (!string.IsNullOrEmpty(BrokerToAdd.firstName))
            {
                if (!Regex.IsMatch(BrokerToAdd.firstName, regexName))
                {
                    ModelState.AddModelError("firstName", "Ecrire un prénom valide");
                }
            }
            else
            {
                ModelState.AddModelError("firstName", "Ecrire un prénom");
            }
            if (!string.IsNullOrEmpty(BrokerToAdd.mail))
            {
                if (!Regex.IsMatch(BrokerToAdd.mail, regexMail))
                {
                    ModelState.AddModelError("mail", "Ecrire une adresse mail valide");
                }
            }
            else
            {
                ModelState.AddModelError("mail", "Ecrire une adresse mail");
            }
            if (!string.IsNullOrEmpty(BrokerToAdd.phoneNumber))
            {
                if (!Regex.IsMatch(BrokerToAdd.phoneNumber, regexPhone))
                {
                    ModelState.AddModelError("phoneNumber", "Ecrire une numero de tel valide");
                }
            }
            else
            {
                ModelState.AddModelError("phoneNumber", "Ecrire une numero de tel");
            }
            if (ModelState.IsValid)
            {
                db.brokers.Add(BrokerToAdd); // insertion dans la dataBase
                db.SaveChanges(); // enregistre les changements
                return RedirectToAction("SuccessAddBroker");
            }
            else
            {
                return View(BrokerToAdd); // Il y'a des erreurs
            }
        }
        public ActionResult SuccessAddBroker()
        {
            return View("SuccessAddBroker");
        }
    }
}

MVC2/Views/Broker/AddBroker.cshtml
@model MVC2.Models.broker
@{
    ViewBag.Title = "AddBroker";
}
<div class="p-3 offset-3">
    <h1 class="display-4 text-capitalize">Ajouter un nouveau Courtier</h1>
    <form action="#" method="post" name="addBroker" id="addBroker" class="offset-2">
        <div class="">
            <div class="form-group">
                <label for="lastName" class="control-label">Nom : </label><input type="text" name="lastName" id="lastName" class="form-control" value="@Request.Form["lastName"]" placeholder="Nom du Courtier" />
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="">
            <div class="form-group"><label for="firstName" class="control-label">Prénom : </label><input type="text" name="firstName" id="firstName" class="form-control" value="@Request.Form["firstName"]" placeholder="Prénom du Courtier" /></div>
            @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
        </div>
        <div class="">
            <div class="form-group"><label for="mail" class="control-label">Adresse Mail : </label><input type="text" name="mail" id="mail" class="form-control" value="@Request.Form["mail"]" placeholder="adresse mail du courtier" /></div>
            @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
        </div>
        <div class="justify-content-center">
            <div class="form-group"><label for="phoneNumber" class="control-label">Numero de tel : </label><input type="text" name="phoneNumber" id="phoneNumber" class="form-control" value="@Request.Form["phoneNumber"]" placeholder="Numero de Tel Courtier" /></div>
            @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
        </div>
        <div class=""><input class="form-control" type="submit" name="submit" id="submit" value="Envoyer" /></div>
    </form>
    @*<div class="p-4 text-center mb-3">
        <h2>Ajouter un nouveau Courtier</h2>
    </div>
    <form action="#" class="pr-5" method="POST">
        <p class="row">
            <label for="lastName" class="col-2">Nom : </label><input type="text" name="lastName" id="lastName" class="col" value="" placeholder="Boby" />
        </p>
        <p class="row"><label for="firstName" class="col-2">Prenom : </label><input type="text" name="firstName" id="firstName" class="col-10" value=" " placeholder="Jones" /></p>
        <p class="row"><label for="phoneNumber" class="col-2">Numero de tel : </label><input type="text" name="phoneNumber" id="phoneNumber" class="col-10" value=" " placeholder="0000000000" /></p>
        <p class="row"><label for="mail" class="col-2">Adresse mail : </label><input type="text" name="mail" id="mail" class="col-10" value=" " placeholder="bobyjones@tanterpian.fr" /></p>
        <p class="text-center"><input type="submit" value="envoyer" /></p>
    </form>*@

    @*<form action="#" method="POST" name="addBroker" id="addBroker">
        <div class="form-horizontal">
            <div class="form-group">
                <label for="lastname" class="control-label">Nom : </label>
                <input class="form-control" type="text" name="lastname" id="lastname" value="@Request.Form["lastname"]" placeholder="Nom" />
                @* Affichage d'un message d'erreur *@
                @*@Html.ValidationMessageFor(model => model.lastname , "", new { @class = "text-danger"})*@
        @*</div>
        <div class="form-group">
            <label for="firstname" class="control-label">Prénom : </label>
            <input class="form-control" type="text" name="firstname" id="firstname" value="@Request.Form["firstname"]" placeholder="Prénom" />*@
            @* Affichage d'un message d'erreur *@
            @*@Html.ValidationMessageFor(model => model.firstname, "", new { @class = "text-danger" })*@
        @*</div>
        <div class="form-group">
            <label for="mail" class="control-label">Mail : </label>
            <input class="form-control" type="email" name="mail" id="mail" value="@Request.Form["mail"]" placeholder="mail" />
            @* Affichage d'un message d'erreur *@
            @*@Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })*@
        @*</div>*@
        @*<div class="form-group">
            <label for="phoneNumber" class="control-label">Téléphone : </label>
            <input class="form-control" type="text" name="phoneNumber" id="phoneNumber" value="@Request.Form["phoneNumber"]" placeholder="Téléphone" />*@
            @* Affichage d'un message d'erreur *@
            @*@Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })*@
        @*</div>
        <div class="form-group">
            <label for="submit" class="control-label"></label>
            <input class="form-control" type="submit" name="submit" id="submit" value="Enregistrer" />
        </div>
    </div>
    </form>*@
</div>

MVC2/Views/Broker/ErrorBadRequest.cshtml
@{
    ViewBag.Title = "ErrorBadRequest";
}

<h2>Herreur de manipulation s'il vous plait retaper votre demande</h2>

MVC2/Views/Broker/ErrorPageNotFound.cshtml
@{
    ViewBag.Title = "ErrorPageNotFound";
}

<h2>Votre page n'existe pas.</h2>

MVC2/Views/Broker/ListBroker.cshtml
@*Permet l'affichage des données correspondants au model choisi *@
@model IEnumerable<MVC2.Models.broker>
@{
    ViewBag.Title = "ListBroker";
}

<div class="">
    <p class="text-center display-3">Liste des Courtiers</p>
    <table border="1" class="table p-1">
        <thead>
            <tr>
                <th class="p-2">Nom</th>
                <th class="p-2">Prenom</th>
                <th class="p-2">Adresse Mail</th>
                <th class="p-2">Numero de tel</th>
                <th class="p-2"></th>
            </tr>
        </thead>
        <tbody class="text-center">
            @foreach (var person in Model)
            {
                //Genere une liste automatiquement grace a la boucle et au razor qui recupère l'info
                <tr>
                    <td class="p-1">@Html.DisplayFor(modelItem => person.lastName)</td>
                    <td class="p-1">@Html.DisplayFor(modelItem => person.firstName)</td>
                    <td class="p-1">@Html.DisplayFor(modelItem => person.mail)</td>
                    <td class="p-1">@Html.DisplayFor(modelItem => person.phoneNumber)</td>
                    <td class="p-1 bg-dark">
                        @Html.ActionLink("Voir profil", "ProfilBroker", new { id = person.idBroker }) |
                        @Html.ActionLink("Prendre RDV", "AddAppointment", "Appointment", new { id = person.idBroker }, null)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a href="AddBroker" class="btn bg-danger">Ajouter Courtier</a>
</div>

MVC2/Views/Broker/ProfilBroker.cshtml
@model MVC2.Models.broker
@{
    ViewBag.Title = "ProfilBroker";
}


<h2>Voir le profil du courtier</h2>

<form action="#" method="post" name="profilBroker" class="#">
    @*@Html.AntiForgeryToken()*@
    @Html.HiddenFor(model => model.idBroker)
    <p>
        <label for="lastName">Nom : </label>
        <input type="text" name="lastName" id="lastName" class="form-control" value="@Html.Display("lastName")" />       
        @*<input type="text" name="lastName" id="lastName" class="form-control" value="@Html.DisplayFor(model => model.lastName)" />*@ 
        @*<input type="text" name="lastName" id="lastName" class="form-control" value="@Model.lastName" />*@
        @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
    </p>
    <p>
        <label for="firstName">Prénom : </label>
        <input type="text" name="firstName" id="firstName" class="form-control" value="@Html.Display("firstName")" />
        @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
    </p>
    <p>
        <label for="mail">Adresse mail : </label>
        <input type="text" name="mail" id="mail" class="form-control" value="@Html.Display("mail")" />
        @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
    </p>
    <p>
        <label for="phoneNumber">Numero Tel : </label>
        <input type="text" name="phoneNumber" id="phoneNumber" class="form-control" value="@Html.Display("phoneNumber")" />
        @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
    </p>
    <input type="submit" value="MARCHEEEUUUUH" class="btn btn-default btn-dark btn-outline-red"/>
</form>

MVC2/Views/Broker/SuccessAddBroker.cshtml
@{
    ViewBag.Title = "SuccessAddBroker";
}

<p class="text-success text-center font-weight-bold">Votre Courtier a bien été ajouté.</p>